/**
 * ACC-GRAPHITE pass-2 RESEARCH, part 2.
 *
 *  E · THE DASH LAW, RE-AUDITIONED. Pass 1 pinned "a dash pattern longer than its path paints
 *      once in Chromium and four times in WebKit" on the frame ring. Part 1's controlled sweep
 *      (pathLength=1 + dasharray:1 on a 4-vertex rect) came back ENGINE-IDENTICAL at every
 *      dashoffset. So the law's condition is not "period > path" alone. This lane puts the
 *      REAL frame-trace `d` (one M, one Z, 25 vertices, generated by the estate's own
 *      `generateFrameTraceFrames`) on a bare page and re-runs pass 1's own list, both engines.
 *  F · the draw-on at the INNER pass's own radius — part 1 sampled the outer band's radius for
 *      both passes and read a constant, which is a null, not a finding.
 *  G · the tally on a page that wrote nothing else, 9x9 and 16x16: tick-to-rule clearance by
 *      row profile, and the painted ink runs at 16x16 where the arithmetic says the tick is
 *      square.
 */
import { test, expect, type Page } from "@playwright/test";
import { mkdirSync, writeFileSync, readFileSync } from "node:fs";
import sharp from "sharp";

const OUT = new URL("../readings/", import.meta.url).pathname;
const HERE = new URL("./", import.meta.url).pathname;
mkdirSync(OUT, { recursive: true });
const bank = (n: string, v: unknown) => writeFileSync(OUT + n, JSON.stringify(v, null, 1));

interface Raw {
  data: Buffer;
  width: number;
  height: number;
  ch: number;
}
async function shot(
  page: Page,
  clip?: { x: number; y: number; width: number; height: number },
): Promise<Raw> {
  const buf = await page.screenshot({ type: "png", ...(clip ? { clip } : {}) });
  const { data, info } = await sharp(buf)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  return { data, width: info.width, height: info.height, ch: info.channels };
}
const lumAt = (p: Raw, x: number, y: number) => {
  const i = (p.width * y + x) * p.ch;
  return 0.2126 * p.data[i] + 0.7152 * p.data[i + 1] + 0.0722 * p.data[i + 2];
};
function rowRuns(p: Raw, y: number, thresh = 160) {
  const runs: { x0: number; w: number }[] = [];
  let s = -1;
  for (let x = 0; x < p.width; x++) {
    const ink = lumAt(p, x, y) < thresh;
    if (ink && s < 0) s = x;
    if (!ink && s >= 0) {
      runs.push({ x0: s, w: x - s });
      s = -1;
    }
  }
  if (s >= 0) runs.push({ x0: s, w: p.width - s });
  return runs;
}

const FRAME_D = readFileSync(HERE + "frame-trace-d.txt", "utf8").trim();

test("E · the dash law re-auditioned on the REAL frame ring", async ({ page, browserName }) => {
  await page.setViewportSize({ width: 800, height: 800 });
  await page.setContent(`<!doctype html><html><body style="margin:0;background:#fff">
  <svg width="800" height="800" viewBox="-20 -20 1040 1040">
    <path id="p" d="${FRAME_D}" fill="none" stroke="#000" stroke-width="10" pathLength="1000"/>
  </svg></body></html>`);
  // one ring-walk run counter: sample a rectangle just inside the frame's own band
  const walk = async () => {
    const png = await shot(page);
    // the frame rect in screen px: viewBox -20..1020 over 800px -> 0.7692 px/unit
    const s = 800 / 1040;
    const px = (u: number) => Math.round((u + 20) * s);
    const x0 = px(12),
      x1 = px(988),
      y0 = px(0),
      y1 = px(1000);
    const ring: boolean[] = [];
    for (let x = x0; x <= x1; x++) ring.push(lumAt(png, x, y0) < 170);
    for (let y = y0; y <= y1; y++) ring.push(lumAt(png, x1, y) < 170);
    for (let x = x1; x >= x0; x--) ring.push(lumAt(png, x, y1) < 170);
    for (let y = y1; y >= y0; y--) ring.push(lumAt(png, x0, y) < 170);
    let runs = 0;
    for (let i = 0; i < ring.length; i++)
      if (ring[i] && !ring[(i - 1 + ring.length) % ring.length]) runs++;
    return { runs, share: +(ring.filter(Boolean).length / ring.length).toFixed(3) };
  };
  // pass 1's own list, plus the ring's mechanism expressed at pathLength 1000
  const k3 = Array.from({ length: 3 }, () => "190 143.3").join(" ") + " 0 1000";
  const lists = [
    { dash: k3, why: "pass 1's k=3 tally list (period > path)" },
    { dash: "100 4000", why: "pass 1's control (period > path)" },
    { dash: "100 10000", why: "pass 1's control" },
    { dash: "200 3800", why: "pass 1's control" },
    { dash: "400 400", why: "pass 1's control (period < path)" },
    { dash: "50 100", why: "pass 1's control (short repeat)" },
    { dash: "1000 1000", why: "THE SHIPPED FILL GAUGE and join ring's own list" },
    { dash: "none", why: "control" },
  ];
  const rows: unknown[] = [];
  for (const l of lists) {
    for (const off of l.dash === "1000 1000" ? [0, 250, 500, 750] : [0]) {
      await page.evaluate(
        (v) => {
          const p = document.getElementById("p")!;
          p.style.strokeDasharray = v.d;
          p.style.strokeDashoffset = String(v.o);
        },
        { d: l.dash, o: off },
      );
      await page.waitForTimeout(70);
      rows.push({ engine: browserName, dash: l.dash, dashoffset: off, why: l.why, ...(await walk()) });
    }
  }
  bank(`E-dash-real-${browserName}.json`, rows);
  console.log(JSON.stringify(rows, null, 1));
  expect(rows.length).toBeGreaterThan(0);
});

async function boot(page: Page, size = 3) {
  await page.goto(`./?size=${size}&difficulty=HARD`);
  await page.waitForSelector(".sudoku-cell", { timeout: 60000 });
  await page.waitForTimeout(1500);
}
async function style(page: Page, css: string) {
  await page.evaluate((t: string) => {
    let el = document.getElementById("r2diag") as HTMLStyleElement | null;
    if (!el) {
      el = document.createElement("style");
      el.id = "r2diag";
      document.head.appendChild(el);
    }
    el.textContent = t;
  }, css);
  await page.waitForTimeout(200);
}

test("F · the draw-on, each pass at its OWN radius", async ({ page, browserName }) => {
  await page.emulateMedia({ colorScheme: "light", reducedMotion: "no-preference" });
  await boot(page);
  const SLOW = 6000;
  const out: unknown[] = [];
  for (const which of ["outer", "inner"] as const) {
    await page.evaluate(() => (document.activeElement as HTMLElement | null)?.blur());
    await page.waitForTimeout(600);
    await style(
      page,
      `.game-cell:has(input:focus-visible) .cell-ghost-path,
       .game-cell:has(input:focus-visible) .cell-ghost-retrace {
         animation: ghost-draw-on ${SLOW}ms linear backwards !important }
       .game-cell:has(input:focus-visible) .cell-ghost-path { fill: none !important }
       ${which === "outer" ? ".cell-ghost-retrace { display: none !important }" : ""}
       ${which === "inner" ? ".game-cell:has(input:focus-visible) .cell-ghost-path { display: none !important }" : ""}`,
    );
    const cell = await page.evaluate(() => {
      const cells = Array.from(document.querySelectorAll<HTMLElement>(".sudoku-cell"));
      const i = cells.findIndex((c) => !c.querySelector<HTMLInputElement>("input")?.value);
      const c = cells[Math.max(0, i)];
      c.querySelector<HTMLInputElement>("input")?.focus();
      const r = c.getBoundingClientRect();
      return { x: r.x, y: r.y, w: r.width, h: r.height };
    });
    const clip = {
      x: Math.round(cell.x - 6),
      y: Math.round(cell.y - 6),
      width: Math.round(cell.w + 12),
      height: Math.round(cell.h + 12),
    };
    const t0 = Date.now();
    for (const frac of [0.2, 0.4, 0.6, 0.8]) {
      while (Date.now() < t0 + SLOW * frac) await page.waitForTimeout(12);
      const png = await shot(page, clip);
      for (const m of [11, 14, 17, 20, 23]) {
        const w = png.width,
          h = png.height;
        if (m * 2 + 4 >= Math.min(w, h)) continue;
        const ring: boolean[] = [];
        for (let x = m; x < w - m; x++) ring.push(lumAt(png, x, m) < 170);
        for (let y = m; y < h - m; y++) ring.push(lumAt(png, w - m - 1, y) < 170);
        for (let x = w - m - 1; x >= m; x--) ring.push(lumAt(png, x, h - m - 1) < 170);
        for (let y = h - m - 1; y >= m; y--) ring.push(lumAt(png, m, y) < 170);
        let arcs = 0;
        const starts: number[] = [];
        const ends: number[] = [];
        for (let i = 0; i < ring.length; i++) {
          const prev = ring[(i - 1 + ring.length) % ring.length];
          const next = ring[(i + 1) % ring.length];
          if (ring[i] && !prev) {
            arcs++;
            starts.push(+(i / ring.length).toFixed(3));
          }
          if (ring[i] && !next) ends.push(+(i / ring.length).toFixed(3));
        }
        out.push({
          engine: browserName,
          pass: which,
          frac,
          radiusPx: m,
          arcs,
          share: +(ring.filter(Boolean).length / ring.length).toFixed(3),
          starts,
          ends,
        });
      }
    }
  }
  await style(page, "");
  bank(`F-drawon-radius-${browserName}.json`, out);
  console.log(
    JSON.stringify(
      (out as { radiusPx: number }[]).filter((r) => r.radiusPx === 17 || r.radiusPx === 20),
      null,
      1,
    ),
  );
  expect(out.length).toBeGreaterThan(0);
});

test("G · the tally on a clean page, 9x9 and 16x16", async ({ page, browserName }) => {
  await page.emulateMedia({ colorScheme: "light", reducedMotion: "reduce" });
  const rows: unknown[] = [];
  for (const size of [3, 4]) {
    await boot(page, size);
    const meta = await page.evaluate(() => {
      const cells = Array.from(document.querySelectorAll<HTMLElement>(".sudoku-cell"));
      const filled = cells.filter((c) => c.querySelector<HTMLInputElement>("input")?.value).length;
      const grid = document.querySelector<SVGSVGElement>("svg.hand-drawn-grid")!;
      const r = grid.getBoundingClientRect();
      return {
        total: cells.length,
        givens: filled,
        writable: cells.length - filled,
        board: { x: r.x, y: r.y, w: r.width, h: r.height },
      };
    });
    for (const k of [0, 1, 3, 20]) {
      // type exactly k digits into empty cells — nothing else is written on this page
      const typed = await page.evaluate(
        (want: number) => {
          const cells = Array.from(document.querySelectorAll<HTMLElement>(".sudoku-cell"));
          return cells
            .map((c, i) => ({ i, v: c.querySelector<HTMLInputElement>("input")?.value }))
            .filter((c) => !c.v)
            .slice(0, want)
            .map((c) => c.i);
        },
        k - (rows.filter((r) => (r as { size: number }).size === size).length ? 0 : 0),
      );
      if (k > 0) {
        for (const i of typed.slice(0, k)) {
          await page.evaluate((n: number) => {
            document
              .querySelectorAll<HTMLElement>(".sudoku-cell")
              [n].querySelector<HTMLInputElement>("input")
              ?.focus();
          }, i);
          await page.keyboard.type("1");
          await page.waitForTimeout(40);
        }
        await page.evaluate(() => (document.activeElement as HTMLElement | null)?.blur());
        await page.waitForTimeout(700);
      }
      const live = await page.evaluate(() => {
        const paths = Array.from(document.querySelectorAll<SVGPathElement>(".progress-trace"));
        const active = Array.from(document.querySelectorAll<HTMLElement>(".progress-pose")).map(
          (g) => ({
            active: g.classList.contains("is-active"),
            opacity: getComputedStyle(g).opacity,
          }),
        );
        const p = paths[0];
        const cs = p ? getComputedStyle(p) : null;
        const bar = document.querySelector('[role="progressbar"]');
        return {
          poses: active.length,
          activePoses: active.filter((a) => a.active).length,
          pathCount: paths.length,
          subpaths: p ? (p.getAttribute("d")?.match(/M/g) ?? []).length : 0,
          strokeWidth: cs?.strokeWidth ?? null,
          linecap: cs?.strokeLinecap ?? null,
          dash: cs?.strokeDasharray ?? null,
          transform: p
            ? getComputedStyle(p.parentElement as Element).transform
            : null,
          valuetext: bar?.getAttribute("aria-valuetext") ?? null,
        };
      });
      // row profile of the board's top strip: where is the frame rule, where are the ticks?
      const clip = {
        x: Math.round(meta.board.x),
        y: Math.round(meta.board.y - 4),
        width: 300,
        height: 44,
      };
      const png = await shot(page, clip);
      const profile: { y: number; ink: number; runs: number }[] = [];
      for (let y = 0; y < png.height; y++) {
        const r = rowRuns(png, y, 170);
        profile.push({ y, ink: r.reduce((n, q) => n + q.w, 0), runs: r.length });
      }
      const inked = profile.filter((p) => p.ink > 0);
      // the frame rule is the row with the most contiguous ink; ticks are the rows below it
      const ruleRow = profile.reduce((a, b) => (b.ink > a.ink ? b : a), profile[0]);
      const tickRows = inked.filter((p) => p.y > ruleRow.y && p.runs > 1);
      rows.push({
        engine: browserName,
        size,
        board: size === 3 ? "9x9" : "16x16",
        writable: meta.writable,
        givens: meta.givens,
        k,
        live,
        ruleRowY: ruleRow.y,
        ruleRowInk: ruleRow.ink,
        tickRowsY: tickRows.map((t) => t.y),
        tickRunsMax: tickRows.length ? Math.max(...tickRows.map((t) => t.runs)) : 0,
        clearanceRowsRuleToTicks: tickRows.length ? tickRows[0].y - ruleRow.y - 1 : null,
        inkedRows: inked.map((p) => `${p.y}:${p.ink}/${p.runs}`),
      });
    }
  }
  bank(`G-tally-${browserName}.json`, rows);
  console.log(
    JSON.stringify(
      rows.map((r) => {
        const q = r as Record<string, unknown>;
        return {
          board: q.board,
          writable: q.writable,
          k: q.k,
          subpaths: (q.live as Record<string, unknown>).subpaths,
          ruleRowY: q.ruleRowY,
          tickRowsY: q.tickRowsY,
          tickRunsMax: q.tickRunsMax,
          clearance: q.clearanceRowsRuleToTicks,
        };
      }),
      null,
      1,
    ),
  );
  expect(rows.length).toBe(8);
});
