// AUTO-GENERATED by vite.config.ts::sudokuTemplates from its TIERS table. Do not hand-edit.
// The table alone, so a deal can read it without downloading the bank (T9-W8 C10).

export type TierSource = "bank" | "livegen";
export type TierKey = "easy" | "medium" | "hard";

/** Where each (size, difficulty) gets its board. Checked against the bank at build time. */
const TIER_SOURCE: Record<number, Record<TierKey, TierSource>> = {
  "2": { easy: "livegen", medium: "livegen", hard: "livegen" },
  "3": { easy: "livegen", medium: "livegen", hard: "bank" },
  "4": { easy: "bank", medium: "bank", hard: "bank" },
};

/** The declared source for a tier. An undeclared size is a caller bug, never a fallback. */
export function tierSource(n: number, difficulty: TierKey): TierSource {
  const row = TIER_SOURCE[n];
  if (!row)
    throw new Error(
      `sudoku: no tier is declared for size ${n}. the TIERS table in vite.config.ts ` +
        `names ${Object.keys(TIER_SOURCE).join(", ")}. A size the picker offers must be declared.`,
    );
  return row[difficulty];
}
