//! Bipartite assignment COP convenience binding for `csp-solver-wasm`.
//!
//! Thin adapter over [`csp_solver::assignment`] (the Rust
//! [`AssignmentBuilder`](csp_solver::AssignmentBuilder)). This module
//! does no solving of its own — it merely receives a typed-array
//! request from JavaScript, hands it to the upstream fluent builder,
//! and serializes the resulting [`AssignmentSolution`](csp_solver::AssignmentSolution)
//! back across the wasm-bindgen boundary as a plain JS value.
//!
//! ## Layer 2 surface
//!
//! `solveAssignmentCop` is the convenience entry point that
//! `bbnf-buddy` and similar consumers call when they want to solve a
//! "match `n` source rows to `m` target columns under per-cell costs"
//! problem without dealing with the lower-level [`crate::Csp`] API.
//! See the project plan for the contract — the TypeScript shape is
//! auto-generated by wasm-bindgen from [`AssignmentRequest`] and
//! [`AssignmentResponse`] below.
//!
//! ## Why `nodeBudgetMs` is currently advisory
//!
//! The upstream Rust solver caps search by *node count*
//! ([`csp_solver::SolveConfig::node_budget`]), not wall-clock time.
//! Translating a millisecond budget to a node budget would require
//! either a per-call calibration loop or a hardcoded "nodes per
//! millisecond" constant — the former is wasteful for the common
//! sub-millisecond case, the latter is a lie on any machine that
//! isn't the developer's. Until the upstream crate grows a real
//! wall-clock budget, this binding accepts the field for forward
//! compatibility, ignores it, and lets the builder fall back to its
//! default million-node guard. Callers that need a hard cap should
//! use the (currently un-exposed) node-budget setter; we will widen
//! the request shape if/when a real consumer asks for it.

use csp_solver::{AssignmentError, SENTINEL, assignment};
use serde::{Deserialize, Serialize};
use wasm_bindgen::prelude::*;

/// JS-facing request shape for [`solve_assignment_cop`].
///
/// Field names use camelCase across the boundary (`#[serde(rename_all = "camelCase")]`)
/// to match the TypeScript ergonomic. The `cost_matrix` field is
/// row-major and must have length `rows * cols`. `row_roles` /
/// `col_roles` may be empty (treated as a single group of zeros);
/// when non-empty their lengths must match `rows` / `cols`
/// respectively. `hint_pairs` is a flat `[srcRow0, tgtCol0, srcRow1,
/// tgtCol1, ...]` sequence; each pair becomes a hard pin via
/// [`AssignmentBuilder::pin`](csp_solver::AssignmentBuilder::pin).
///
/// `node_budget_ms` is accepted for forward compatibility but is
/// currently ignored — see the module docs for the rationale.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AssignmentRequest {
    /// Row-major cost matrix, length must equal `rows * cols`.
    pub cost_matrix: Vec<f64>,
    /// Number of source rows.
    pub rows: usize,
    /// Number of target columns.
    pub cols: usize,
    /// Per-row group tag. Empty (default) means a single group of
    /// zeros for every row.
    #[serde(default)]
    pub row_roles: Vec<u8>,
    /// Per-col group tag. Empty (default) means a single group of
    /// zeros for every column.
    #[serde(default)]
    pub col_roles: Vec<u8>,
    /// Flat hint pairs `[srcRow0, tgtCol0, srcRow1, tgtCol1, ...]`.
    /// Length must be even. Empty by default.
    #[serde(default)]
    pub hint_pairs: Vec<i32>,
    /// Cost penalty per unmatched row. Defaults to `0.0`.
    #[serde(default)]
    pub unmatch_penalty: f64,
    /// Optional wall-clock budget in milliseconds. **Currently
    /// ignored** — see the module-level docs.
    #[serde(default)]
    pub node_budget_ms: Option<u32>,
}

/// JS-facing response shape returned by [`solve_assignment_cop`].
///
/// The `assign` vector has length `rows`; each entry is the assigned
/// column index, or [`SENTINEL`] (`-1`) if the row was left
/// unmatched. `cost` is the total cost the solver computed by summing
/// the per-cell entries plus
/// [`unmatch_penalty`](AssignmentRequest::unmatch_penalty) for each
/// `SENTINEL` row. `nodes_explored` and `budget_exceeded` come
/// straight from the underlying
/// [`SolveStats`](csp_solver::SolveStats); inspect `budget_exceeded`
/// to distinguish a best-so-far from an optimal answer.
///
/// Both `Serialize` and `Deserialize` are derived so the type can
/// round-trip across `serde-wasm-bindgen` in either direction — the
/// wasm-pack `--node` test suite uses the deserialize path to assert
/// against brute-force enumeration.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AssignmentResponse {
    /// Per-row assignment; length equals `rows`. `-1` (the
    /// [`SENTINEL`] constant) means unmatched.
    pub assign: Vec<i32>,
    /// Total assignment cost: per-cell entries plus
    /// `unmatch_penalty` per unmatched row.
    pub cost: f64,
    /// Number of branch-and-bound search nodes explored.
    pub nodes_explored: u64,
    /// `true` when the underlying search hit its node budget and
    /// returned best-so-far rather than optimal results.
    pub budget_exceeded: bool,
}

/// Solve a bipartite assignment COP from a JS request object.
///
/// Validates the request, delegates to
/// [`csp_solver::assignment`], and serializes the resulting
/// [`AssignmentSolution`](csp_solver::AssignmentSolution) back as a
/// JS value. All error paths surface as a `JsError` (a JavaScript
/// `Error` instance on the consuming side).
///
/// See [`AssignmentRequest`] / [`AssignmentResponse`] for the wire
/// shapes; the TypeScript bindings are auto-generated by
/// wasm-bindgen from those structs.
#[wasm_bindgen(js_name = solveAssignmentCop)]
pub fn solve_assignment_cop(req: JsValue) -> Result<JsValue, JsError> {
    let req: AssignmentRequest = serde_wasm_bindgen::from_value(req)
        .map_err(|e| JsError::new(&format!("invalid AssignmentRequest: {e}")))?;

    // Shape validation up front so the failure mode is a clear JS
    // exception rather than an opaque panic from the builder.
    if req.rows == 0 || req.cols == 0 {
        return Err(JsError::new("rows and cols must both be > 0"));
    }
    if req.cost_matrix.len() != req.rows * req.cols {
        return Err(JsError::new(&format!(
            "costMatrix.length ({}) must equal rows * cols ({} * {} = {})",
            req.cost_matrix.len(),
            req.rows,
            req.cols,
            req.rows * req.cols
        )));
    }
    if !req.row_roles.is_empty() && req.row_roles.len() != req.rows {
        return Err(JsError::new(&format!(
            "rowRoles.length ({}) must equal rows ({}) or be empty",
            req.row_roles.len(),
            req.rows
        )));
    }
    if !req.col_roles.is_empty() && req.col_roles.len() != req.cols {
        return Err(JsError::new(&format!(
            "colRoles.length ({}) must equal cols ({}) or be empty",
            req.col_roles.len(),
            req.cols
        )));
    }
    if req.hint_pairs.len() % 2 != 0 {
        return Err(JsError::new(&format!(
            "hintPairs.length ({}) must be even — pairs are flat [srcRow, tgtCol, ...]",
            req.hint_pairs.len()
        )));
    }

    // Decompose the request into the pieces the builder closures
    // capture. Cloning the role slices keeps the closure
    // `'static + Send + Sync` and avoids borrowing from `req` after
    // the cost matrix has been moved into the cost closure.
    let cost = req.cost_matrix;
    let cols = req.cols;
    let rows = req.rows;
    let row_roles = req.row_roles;
    let col_roles = req.col_roles;

    let mut b = assignment()
        .rows(rows)
        .cols(cols)
        .cost(|i, k| cost[i * cols + k])
        .unmatch_penalty(req.unmatch_penalty);

    if !row_roles.is_empty() {
        b = b.row_group(move |i| row_roles[i]);
    }
    if !col_roles.is_empty() {
        b = b.col_group(move |k| col_roles[k]);
    }
    for chunk in req.hint_pairs.chunks_exact(2) {
        b = b.pin(chunk[0] as usize, chunk[1]);
    }

    // `node_budget_ms` is intentionally ignored — see module docs.
    // Letting the builder install its default million-node guard is
    // the right behaviour until upstream grows a wall-clock budget.
    let _ = req.node_budget_ms;

    let sol = b
        .solve()
        .map_err(|e: AssignmentError| JsError::new(&format!("{e}")))?;

    let response = AssignmentResponse {
        assign: sol.assign,
        cost: sol.cost,
        nodes_explored: sol.stats.nodes_explored,
        budget_exceeded: sol.stats.budget_exceeded,
    };

    serde_wasm_bindgen::to_value(&response)
        .map_err(|e| JsError::new(&format!("serialize AssignmentResponse: {e}")))
}

/// Re-export the unmatched-row sentinel so JS-side callers can
/// reference the constant by name instead of hard-coding `-1`.
///
/// Mirrors [`csp_solver::SENTINEL`]. Exposed as a wasm-bindgen
/// function (rather than a `#[wasm_bindgen]` constant, which the
/// macro does not support for primitive integers) so the generated
/// `.d.ts` carries the documentation alongside the value.
#[wasm_bindgen(js_name = assignmentSentinel)]
pub fn assignment_sentinel() -> i32 {
    SENTINEL
}
