import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import vue from '@vitejs/plugin-vue'
import tailwindcss from '@tailwindcss/vite'
import autoprefixer from 'autoprefixer'
import path from 'path'
import { defineConfig, type Plugin } from 'vite'
import { VitePWA } from 'vite-plugin-pwa'

/**
 * `sudoku-templates` — the build rule that DERIVES
 * `src/games/sudoku/data/templates.ts` from the canonical puzzle-template
 * bank. Runs on both `vite` (serve) and `vite build` via `buildStart`.
 *
 * `templates.ts` is a generated artifact, never hand-edited and never a
 * fork of the JSON. The single source of truth is the bank the solver
 * itself owns (W4 embedded it into the crate via `include_dir`):
 *
 *   csp-solver/data/sudoku_puzzles/{n}/{difficulty}/template-*.json
 *
 * (the `puzzle` field — a position-keyed map of the given clues, `0`
 * elsewhere). Flip the single `SRC_REL` constant if the bank ever moves
 * again; never copy JSON by hand (wave §Residual). This plugin lives in
 * `vite.config.ts` — the Node build context that isn't compiled by the
 * browser `tsconfig` — so its `node:fs`/`node:path` use never reaches the
 * app typecheck.
 */
function sudokuTemplates(): Plugin {
  const SRC_REL = '../../csp-solver/data/sudoku_puzzles'
  const OUT_REL = 'src/games/sudoku/data/templates.ts'
  // W4 (tranche-2) reshaped the bank: N=2 (all tiers), N=3-easy, N=3-medium, and
  // the whole N=5 subtree were excised — the fast-path bank now ships only the
  // tiers whose native generate breaches the in-browser budget (N=3-hard, N=4-*).
  // Excised (size,difficulty) pairs have no on-disk directory; the frontend
  // live-generates them via wasm (`TEMPLATE_BANK[size]?.[…] ?? []`). SIZES lists
  // the sizes with *any* surviving bank; the per-difficulty `existsSync` guard
  // below tolerates the missing tiers within a surviving size (N=3 keeps only hard).
  const SIZES = [3, 4]
  const DIFFICULTIES = ['easy', 'medium', 'hard'] as const

  function render(srcDir: string): string {
    const bank: Record<number, Record<string, number[][]>> = {}
    let totalBoards = 0
    let rawCells = 0
    for (const n of SIZES) {
      bank[n] = { easy: [], medium: [], hard: [] }
      const total = (n * n) ** 2
      for (const d of DIFFICULTIES) {
        const dir = join(srcDir, String(n), d)
        // Excised tier (git-rm'd by W4) → no directory → empty bank entry →
        // the frontend falls back to wasm live-gen. Never let a missing dir throw.
        if (!existsSync(dir)) {
          bank[n][d] = []
          continue
        }
        const files = readdirSync(dir)
          .filter((f: string) => f.startsWith('template-') && f.endsWith('.json'))
          .sort()
        const boards: number[][] = []
        for (const f of files) {
          const data = JSON.parse(readFileSync(join(dir, f), 'utf8')) as {
            puzzle: Record<string, number>
          }
          const flat = new Array<number>(total).fill(0)
          for (const [k, v] of Object.entries(data.puzzle)) flat[Number(k)] = v
          boards.push(flat)
        }
        bank[n][d] = boards
        totalBoards += boards.length
        rawCells += boards.length * total
      }
    }
    const banner =
      `// AUTO-GENERATED by vite.config.ts::sudokuTemplates from\n` +
      `// ${SRC_REL}/{n}/{difficulty}/template-*.json (\`puzzle\` field).\n` +
      `// ${totalBoards} boards, ${rawCells} u32 cells total. Do not hand-edit.\n`
    return (
      `${banner}\n` +
      `export type TemplateBank = Record<number, Record<'easy' | 'medium' | 'hard', number[][]>>\n\n` +
      `export const TEMPLATE_BANK: TemplateBank = ${JSON.stringify(bank)}\n`
    )
  }

  let root = process.cwd()
  return {
    name: 'sudoku-templates',
    configResolved(config) {
      root = config.root
    },
    buildStart() {
      const outPath = resolve(root, OUT_REL)
      const next = render(resolve(root, SRC_REL))
      const existing = ((): string | null => {
        try {
          return readFileSync(outPath, 'utf8')
        } catch {
          return null
        }
      })()
      // Write only on drift — a no-op steady state keeps the dev watcher
      // from looping on its own emit.
      if (existing !== next) writeFileSync(outPath, next)
    },
  }
}

export default defineConfig({
  base: process.env.VITE_BASE_URL || '/',
  resolve: {
    alias: {
      '@pencil': path.resolve(__dirname, './src/pencil'),
      '@games': path.resolve(__dirname, './src/games'),
      '@': path.resolve(__dirname, './src'),
    },
  },
  css: {
    postcss: {
      plugins: [autoprefixer()],
    },
  },
  plugins: [
    vue(),
    tailwindcss(),
    sudokuTemplates(),
    // T2-W6 PWA-minimal (Q4's written SW strategy). generateSW precache ONLY —
    // no runtime sync, no update toasts. `autoUpdate` = silent skipWaiting +
    // clientsClaim; `injectRegister: 'script'` emits an external `/registerSW.js`
    // (never an inline <script>) so the CSP `script-src 'self'` — no
    // 'unsafe-inline' — admits the registration.
    VitePWA({
      registerType: 'autoUpdate',
      strategies: 'generateSW',
      injectRegister: 'script',
      workbox: {
        // MANDATORY widening (Q4): the plugin default `{js,wasm,css,html}`
        // precaches the hashed wasm but SILENTLY DROPS the P5 self-hosted woff2
        // faces and `favicon.svg` — an offline reload would render in system
        // fonts, negating the fonts-before-PWA sequencing. `svg` also catches
        // the favicon. `png` is deliberately OMITTED (the manifest icons ride
        // in via `includeManifestIcons`, and the glob stays Q4-verbatim).
        globPatterns: ['**/*.{js,css,html,wasm,woff2,svg}'],
        // Plugin defaults, pinned for the record: hashed `/assets/*` URLs are
        // the version, so they precache as `revision:null` (no `__WB_REVISION__`
        // cache-bust query — byte-identical to the W5 immutable-cached URL).
        dontCacheBustURLsMatching: /^assets\//,
        // Evict superseded wasm/font hashes from Cache Storage on activate.
        cleanupOutdatedCaches: true,
        navigateFallback: 'index.html',
        // NO `runtimeCaching` route on `/assets/*` — precache IS the strategy
        // for hashed assets; a second CacheFirst route would double-store the
        // wasm and fight precache. NO `maximumFileSizeToCacheInBytes` bump
        // (the lean wasm ~87 KB ≪ the 2 MiB default ceiling).
      },
      manifest: {
        name: 'Sudoku — CSP Solver',
        short_name: 'Sudoku',
        description: 'Hand-drawn Sudoku & Futoshiki, solved in your browser.',
        // Q7: pin `start_url` so icon launches always take the clean
        // fresh/storage precedence — never replay a captured `?board=`.
        start_url: '/',
        display: 'standalone',
        // Pencil palette: cream paper (`hsl(48 15% 98%)` ≈ #faf8f5, the favicon
        // background rect) for both the splash background and the toolbar tint.
        background_color: '#faf8f5',
        theme_color: '#faf8f5',
        icons: [
          { src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' },
          { src: 'pwa-512x512.png', sizes: '512x512', type: 'image/png' },
          {
            src: 'pwa-maskable-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
          { src: 'favicon.svg', sizes: 'any', type: 'image/svg+xml' },
        ],
      },
    }),
  ],
  // W6 Option C: `solver.worker.ts` is an ES-module Worker (`{ type: 'module' }`)
  // that top-level-imports the wasm glue — the production Worker bundle must be
  // ESM, not the default IIFE.
  worker: {
    format: 'es',
  },
  // The wasm-bindgen `--target web` module (`@mkbabb/csp-solver-wasm`, a `file:`
  // link to the local pkg) resolves its `.wasm` via `new URL(..., import.meta.url)`;
  // esbuild's dep pre-bundling mangles that, so keep it out of optimizeDeps and let
  // Vite's asset pipeline emit the wasm binary in the Worker graph.
  optimizeDeps: {
    exclude: ['@mkbabb/csp-solver-wasm'],
  },
  server: {
    port: 3000,
    host: '0.0.0.0',
    // The wasm binary the solver Worker `?url`-imports lives in the local
    // `@mkbabb/csp-solver-wasm` pkg — a `file:` dep symlinked to
    // `csp-solver/wasm/pkg`, which Vite resolves to a real path *outside* the
    // frontend root. Without this the dev server 403s the `.wasm` fetch
    // ("outside of Vite serving allow list") and the Worker can't instantiate.
    // Retire this entry when W12 swaps the `file:` link for the published
    // registry package (then the pkg lives under node_modules inside root).
    fs: {
      allow: [path.resolve(__dirname), path.resolve(__dirname, '../../csp-solver/wasm/pkg')],
    },
    hmr: {
      host: 'localhost',
      port: 3000,
    },
    proxy: {
      '/api': {
        target: process.env.VITE_API_URL || `http://localhost:${process.env.VITE_API_PORT || '8000'}`,
        changeOrigin: true,
      },
    },
  },
  build: {
    target: 'es2020',
    minify: 'esbuild',
    // P5 (Tranche II): never base64-inline the self-hosted font subsets. The default
    // 4KB assetsInlineLimit would otherwise fold firacode-subset.woff2 (3,624 B) and
    // patrickhand-subset.woff2 (3,840 B) into the CSS as base64 — ~33% bigger on the
    // wire AND no longer independently cacheable (they'd get re-fetched on every
    // CSS-touching deploy instead of sitting behind their own immutable, content-
    // hashed /assets/*.woff2 URL — the W5 cache-header beat this self-host feeds).
    assetsInlineLimit: (filePath) => (filePath.endsWith('.woff2') ? false : undefined),
    rollupOptions: {
      output: {
        // Rolldown (Vite 8's default bundler) rejects the classic object-literal
        // `manualChunks` form outright (`TypeError: manualChunks is not a function`) —
        // the function form is its only supported shape. Match both `vue/` and `@vue/`
        // because modern Vue (3.4+) ships `vue` as a thin re-export shell over separately
        // resolvable `@vue/*` modules. keyframes.js was dropped from the app runtime by
        // W8's 4th workstream (grid + glyph draw-in migrated off `KeyframesAnimation` onto
        // the unified scheduler's `sequence` subscriber), so it no longer enters any chunk —
        // only pencil-boil remains as the animation vendor.
        manualChunks(id) {
          if (id.includes('/node_modules/vue/') || id.includes('/node_modules/@vue/')) {
            return 'vue-vendor'
          }
          if (id.includes('/node_modules/@mkbabb/pencil-boil/')) {
            return 'animation-vendor'
          }
        },
      },
    },
  },
})
