import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import vue from '@vitejs/plugin-vue'
import tailwindcss from '@tailwindcss/vite'
import autoprefixer from 'autoprefixer'
import path from 'path'
import { defineConfig, type Plugin } from 'vite'

/**
 * `sudoku-templates` — the build rule that DERIVES
 * `src/games/sudoku/data/templates.ts` from the canonical puzzle-template
 * bank. Runs on both `vite` (serve) and `vite build` via `buildStart`.
 *
 * `templates.ts` is a generated artifact, never hand-edited and never a
 * fork of the JSON. The single source of truth is the bank the solver
 * itself owns (W4 embedded it into the crate via `include_dir`):
 *
 *   csp-solver/data/sudoku_puzzles/{n}/{difficulty}/template-*.json
 *
 * (the `puzzle` field — a position-keyed map of the given clues, `0`
 * elsewhere). Flip the single `SRC_REL` constant if the bank ever moves
 * again; never copy JSON by hand (wave §Residual). This plugin lives in
 * `vite.config.ts` — the Node build context that isn't compiled by the
 * browser `tsconfig` — so its `node:fs`/`node:path` use never reaches the
 * app typecheck.
 */
function sudokuTemplates(): Plugin {
  const SRC_REL = '../../csp-solver/data/sudoku_puzzles'
  const OUT_REL = 'src/games/sudoku/data/templates.ts'
  const SIZES = [2, 3, 4]
  const DIFFICULTIES = ['easy', 'medium', 'hard'] as const

  function render(srcDir: string): string {
    const bank: Record<number, Record<string, number[][]>> = {}
    let totalBoards = 0
    let rawCells = 0
    for (const n of SIZES) {
      bank[n] = { easy: [], medium: [], hard: [] }
      const total = (n * n) ** 2
      for (const d of DIFFICULTIES) {
        const dir = join(srcDir, String(n), d)
        const files = readdirSync(dir)
          .filter((f: string) => f.startsWith('template-') && f.endsWith('.json'))
          .sort()
        const boards: number[][] = []
        for (const f of files) {
          const data = JSON.parse(readFileSync(join(dir, f), 'utf8')) as {
            puzzle: Record<string, number>
          }
          const flat = new Array<number>(total).fill(0)
          for (const [k, v] of Object.entries(data.puzzle)) flat[Number(k)] = v
          boards.push(flat)
        }
        bank[n][d] = boards
        totalBoards += boards.length
        rawCells += boards.length * total
      }
    }
    const banner =
      `// AUTO-GENERATED by vite.config.ts::sudokuTemplates from\n` +
      `// ${SRC_REL}/{n}/{difficulty}/template-*.json (\`puzzle\` field).\n` +
      `// ${totalBoards} boards, ${rawCells} u32 cells total. Do not hand-edit.\n`
    return (
      `${banner}\n` +
      `export type TemplateBank = Record<number, Record<'easy' | 'medium' | 'hard', number[][]>>\n\n` +
      `export const TEMPLATE_BANK: TemplateBank = ${JSON.stringify(bank)}\n`
    )
  }

  let root = process.cwd()
  return {
    name: 'sudoku-templates',
    configResolved(config) {
      root = config.root
    },
    buildStart() {
      const outPath = resolve(root, OUT_REL)
      const next = render(resolve(root, SRC_REL))
      const existing = ((): string | null => {
        try {
          return readFileSync(outPath, 'utf8')
        } catch {
          return null
        }
      })()
      // Write only on drift — a no-op steady state keeps the dev watcher
      // from looping on its own emit.
      if (existing !== next) writeFileSync(outPath, next)
    },
  }
}

export default defineConfig({
  base: process.env.VITE_BASE_URL || '/',
  resolve: {
    alias: {
      '@pencil': path.resolve(__dirname, './src/pencil'),
      '@games': path.resolve(__dirname, './src/games'),
      '@': path.resolve(__dirname, './src'),
    },
  },
  css: {
    postcss: {
      plugins: [autoprefixer()],
    },
  },
  plugins: [vue(), tailwindcss(), sudokuTemplates()],
  // W6 Option C: `solver.worker.ts` is an ES-module Worker (`{ type: 'module' }`)
  // that top-level-imports the wasm glue — the production Worker bundle must be
  // ESM, not the default IIFE.
  worker: {
    format: 'es',
  },
  // The wasm-bindgen `--target web` module (`@mkbabb/csp-solver-wasm`, a `file:`
  // link to the local pkg) resolves its `.wasm` via `new URL(..., import.meta.url)`;
  // esbuild's dep pre-bundling mangles that, so keep it out of optimizeDeps and let
  // Vite's asset pipeline emit the wasm binary in the Worker graph.
  optimizeDeps: {
    exclude: ['@mkbabb/csp-solver-wasm'],
  },
  server: {
    port: 3000,
    host: '0.0.0.0',
    // The wasm binary the solver Worker `?url`-imports lives in the local
    // `@mkbabb/csp-solver-wasm` pkg — a `file:` dep symlinked to
    // `csp-solver/wasm/pkg`, which Vite resolves to a real path *outside* the
    // frontend root. Without this the dev server 403s the `.wasm` fetch
    // ("outside of Vite serving allow list") and the Worker can't instantiate.
    // Retire this entry when W12 swaps the `file:` link for the published
    // registry package (then the pkg lives under node_modules inside root).
    fs: {
      allow: [path.resolve(__dirname), path.resolve(__dirname, '../../csp-solver/wasm/pkg')],
    },
    hmr: {
      host: 'localhost',
      port: 3000,
    },
    proxy: {
      '/api': {
        target: process.env.VITE_API_URL || `http://localhost:${process.env.VITE_API_PORT || '8000'}`,
        changeOrigin: true,
      },
    },
  },
  build: {
    target: 'es2020',
    minify: 'esbuild',
    // P5 (Tranche II): never base64-inline the self-hosted font subsets. The default
    // 4KB assetsInlineLimit would otherwise fold firacode-subset.woff2 (3,624 B) and
    // patrickhand-subset.woff2 (3,840 B) into the CSS as base64 — ~33% bigger on the
    // wire AND no longer independently cacheable (they'd get re-fetched on every
    // CSS-touching deploy instead of sitting behind their own immutable, content-
    // hashed /assets/*.woff2 URL — the W5 cache-header beat this self-host feeds).
    assetsInlineLimit: (filePath) => (filePath.endsWith('.woff2') ? false : undefined),
    rollupOptions: {
      output: {
        // Rolldown (Vite 8's default bundler) rejects the classic object-literal
        // `manualChunks` form outright (`TypeError: manualChunks is not a function`) —
        // the function form is its only supported shape. Match both `vue/` and `@vue/`
        // because modern Vue (3.4+) ships `vue` as a thin re-export shell over separately
        // resolvable `@vue/*` modules. keyframes.js was dropped from the app runtime by
        // W8's 4th workstream (grid + glyph draw-in migrated off `KeyframesAnimation` onto
        // the unified scheduler's `sequence` subscriber), so it no longer enters any chunk —
        // only pencil-boil remains as the animation vendor.
        manualChunks(id) {
          if (id.includes('/node_modules/vue/') || id.includes('/node_modules/@vue/')) {
            return 'vue-vendor'
          }
          if (id.includes('/node_modules/@mkbabb/pencil-boil/')) {
            return 'animation-vendor'
          }
        },
      },
    },
  },
})
