#!/usr/bin/env bash
# ci-conclusion.sh — pin a CI run to a SHA, read its conclusion, bank the artifact.
#
# CH-57 (the owned process fault): a gated chain must never decide on an echo
# downstream of a pipe. Here the conclusion is read by its OWN `gh run view
# --json conclusion` invocation, assigned to a variable, and the exit status is
# decided from that variable alone. The listing call resolves the run id only —
# it is never asked for the verdict.
#
# The artifact this writes is the token `scripts/deploy-gated.sh` demands.
#
# T7-W6 — RERUN LAUNDERING. A conclusion is a verdict on ONE attempt of ONE run, and a
# SHA can carry many of both. `runs_for_sha` has been banked since T5-W6.2 and nothing
# read it; `run_attempt` was never banked at all, so a run red on attempt 1 and re-run
# until attempt 3 came out green wrote an artifact byte-identical to a first-try green.
# Both numbers now ride in the artifact and deploy-gated.sh refuses on either unless the
# artifact carries an explicit `reruns_permitted yes` declaration (hand-added, never by
# this generator). The count is the evidence; the declaration is the owner saying so.
#
# Usage:
#   scripts/ci-conclusion.sh --out <path> [--sha <rev>] [--workflow <file>]
#
#   --out       where to write the conclusion artifact (required)
#   --sha       any git rev; defaults to HEAD. Resolved to a full 40-char SHA.
#   --workflow  workflow file name; defaults to ci.yml
#
# Exit: 0 only when the pinned run's conclusion is exactly "success".
#       1 the run resolved but did not conclude success (artifact still written)
#       2 usage error
#       3 no run found for that SHA, or the pin did not hold
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

SHA=""
OUT=""
WORKFLOW="ci.yml"

# The header block above IS the usage text — print it, never a second copy of it.
usage() {
    awk 'NR>1 && /^#/ { sub(/^# ?/, ""); print; next } NR>1 { exit }' "${BASH_SOURCE[0]}"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --sha)      SHA="${2:?--sha needs a value}"; shift 2 ;;
        --out)      OUT="${2:?--out needs a value}"; shift 2 ;;
        --workflow) WORKFLOW="${2:?--workflow needs a value}"; shift 2 ;;
        -h|--help)  usage; exit 0 ;;
        *) echo "ci-conclusion: unknown argument: $1" >&2; usage >&2; exit 2 ;;
    esac
done

[[ -n "$OUT" ]] || { echo "ci-conclusion: --out <path> is required" >&2; exit 2; }

cd "$ROOT"

# ── Pin: resolve the rev to a full SHA ────────────────────
SHA="$(git rev-parse "${SHA:-HEAD}")"

# ── Resolve the run for that SHA (id only — never the verdict) ──
# @tsv keeps the read to one API call and one variable assignment; `length`
# rides along so a zero-run answer is distinguishable from a null-field one.
LIST_TSV="$(gh run list --workflow "$WORKFLOW" --commit "$SHA" --limit 20 \
    --json databaseId,headSha,status,createdAt,url \
    --jq '[(.[0].databaseId // ""), (.[0].headSha // ""), (.[0].status // ""), (.[0].createdAt // ""), (.[0].url // ""), (length | tostring)] | @tsv')"

IFS=$'\t' read -r RUN_ID RUN_SHA RUN_STATUS RUN_CREATED RUN_URL RUN_COUNT <<<"$LIST_TSV"

if [[ -z "$RUN_ID" || "${RUN_COUNT:-0}" == "0" ]]; then
    echo "ci-conclusion: no $WORKFLOW run found for $SHA" >&2
    exit 3
fi

# The pin has to hold on the run's own headSha, not on the query alone.
if [[ "$RUN_SHA" != "$SHA" ]]; then
    echo "ci-conclusion: pin broke — asked $SHA, run $RUN_ID reports $RUN_SHA" >&2
    exit 3
fi

# ── The conclusion, in its own invocation, into its own variable ──
CONCLUSION="$(gh run view "$RUN_ID" --json conclusion --jq '.conclusion // ""')"

# ── The attempt, likewise its own read ────────────────────────────
# `attempt` is 1 on a first-try verdict and >1 once someone pressed re-run. An empty
# answer is banked as `unknown`, which the deploy gate treats as a refusal — a field the
# gate cannot read must never default to the permissive value.
ATTEMPT="$(gh run view "$RUN_ID" --json attempt --jq '.attempt // ""')"
ATTEMPT="${ATTEMPT:-unknown}"

# ── Bank the artifact ─────────────────────────────────────
NOW_ISO="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
NOW_EPOCH="$(date -u +%s)"

mkdir -p "$(dirname "$OUT")"
cat >"$OUT" <<EOF
# CI conclusion artifact — generated by scripts/ci-conclusion.sh
# The token scripts/deploy-gated.sh requires. Fields are "key<space>value";
# deploy-gated.sh reads sha, conclusion, timestamp_epoch, runs_for_sha and
# run_attempt, and refuses on any of: sha != HEAD, conclusion != success,
# age >= 24h, runs_for_sha != 1, run_attempt != 1.
#
# The last two refusals lift only on an explicit, hand-added declaration:
#   reruns_permitted yes
# plus a `reruns_reason <one line>` line. This generator never writes either —
# a laundered green has to be signed for.
sha             $SHA
run_id          $RUN_ID
run_url         $RUN_URL
workflow        $WORKFLOW
status          $RUN_STATUS
conclusion      $CONCLUSION
run_created_at  $RUN_CREATED
runs_for_sha    $RUN_COUNT
run_attempt     $ATTEMPT
timestamp       $NOW_ISO
timestamp_epoch $NOW_EPOCH
generator       scripts/ci-conclusion.sh
EOF

# ── Decide from the variable, never from a pipe ───────────
if [[ "$CONCLUSION" == "success" ]]; then
    echo "[ci-conclusion] $SHA -> run $RUN_ID -> success"
    echo "[ci-conclusion] runs for this sha: $RUN_COUNT · attempt: $ATTEMPT"
    if [[ "$RUN_COUNT" != "1" || "$ATTEMPT" != "1" ]]; then
        echo "[ci-conclusion] NOTE — this green is not the sha's only conclusion." >&2
        echo "[ci-conclusion] The deploy gate will REFUSE it without a 'reruns_permitted yes' declaration." >&2
    fi
    echo "[ci-conclusion] artifact: $OUT"
    exit 0
fi

echo "[ci-conclusion] $SHA -> run $RUN_ID -> conclusion '${CONCLUSION:-<none>}' (status $RUN_STATUS) — not success" >&2
echo "[ci-conclusion] artifact written anyway (it will be REFUSED by the deploy gate): $OUT" >&2
exit 1
